language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules

before_install:
  - npm install -g greenkeeper-lockfile@1
  - npm install -g gulp-cli

before_script:
  - greenkeeper-lockfile-update

script:
  - npm test

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info

addons:
  code_climate:
    repo_token: ee3f5e835f78fb8235760be0cdd222d16a98f93c784bb5b8f38e59090544c5b2

env:
  - COOKIE_VALIDATION_PASSWORD=7044a01fe9e9e4960eb9be8c75bc61ca6360b2adb0cd84673f51da0e16b65249c04f5f358b4bfbcc03b64cce6baa95172148b68a5ac354d8153b60804ec09943
